### ISSUE TITLE
Invalid direction for tail segment after hitting the LHS of the screen.

### ISSUE THREAD

**Issue by cgaebel** [bfops/Snake#23]
Steps to reproduce:
1. Get a fertility test for you and one human female.
2. If both positive, fuck human female.
3. If female is still not preggers, return to step 2.

But in all seriousness, just hit the left wall while in gdb. You'll see...

GingerbreadPrototype: /home/clark/dev/cpp/gingerbread/Main/Bounds.cpp:79: Side Bounds::GetSide(Direction) const: Assertion `validDirection(whichSide)' failed.

Program received signal SIGABRT, Aborted.
0x00007ffff6e8b2c5 in raise () from /lib/libc.so.6
(gdb) bt
#0  0x00007ffff6e8b2c5 in raise () from /lib/libc.so.6
#1  0x00007ffff6e8c56a in abort () from /lib/libc.so.6
#2  0x00007ffff6e84045 in __assert_fail () from /lib/libc.so.6
#3  0x000000000042bf17 in Bounds::GetSide (this=0x69e6a4, whichSide=...) at /home/clark/dev/cpp/gingerbread/Main/Bounds.cpp:79
#4  0x0000000000442acb in SnakeSegment::GetTailSide (this=0x69e690) at /home/clark/dev/cpp/gingerbread/Main/SnakeSegment.cpp:123
#5  0x0000000000442765 in SnakeSegment::ModifyLength (this=0x69e690, amount=-1) at /home/clark/dev/cpp/gingerbread/Main/SnakeSegment.cpp:59
#6  0x0000000000442897 in SnakeSegment::operator-- (this=0x69e690) at /home/clark/dev/cpp/gingerbread/Main/SnakeSegment.cpp:83
#7  0x000000000043fc4d in Snake::Update (this=0x7fffffffdc30, world=...) at /home/clark/dev/cpp/gingerbread/Main/Snake.cpp:139
#8  0x000000000042d2b4 in GameWorld::Update (this=0x7fffffffdb90) at /home/clark/dev/cpp/gingerbread/Main/GameWorld.cpp:166
#9  0x0000000000431286 in main_loop (gameWorld=...) at /home/clark/dev/cpp/gingerbread/Main/main.cpp:25
#10 0x00000000004313b3 in main () at /home/clark/dev/cpp/gingerbread/Main/main.cpp:46

And we see the invalid direction (0, 0) coming from SnakeSegment::GetTailSide. It seems to be an uninitialized direction being used.

**Comment by bfops** [comment]
Verified when hitting top, too.
This only occurs sometimes, strange.

**Comment by bfops** [comment]
I believe it's fixed; it's hard to know because it's not always reproducible.
