### ISSUE TITLE
Logger(null)

### ISSUE THREAD

**Issue by bfops** [bfops/Snake#7]
When logging to World::logger, the tag appears as "null" for some time, before finally switching to "World". Copy-constructing the Logger rather than assigning it makes no difference.

**Comment by cgaebel** [comment]
I wtf'd.

**Comment by bfops** [comment]
Have you run the program?

**Comment by cgaebel** [comment]
No busy today.

**Comment by bfops** [comment]
Closed; bug was due to crappy initialization - see
http://github.com/RobotGymnast/Gingerbread/issues#issue/11
